name: Python CI
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Install bench
      run: |
        pip install -e git+https://github.com/frappe/bench.git#egg=bench

    - name: Setup Frappe environment
      run: |
        bench init --skip-redis-config-generation frappe-bench
        cd frappe-bench
        bench get-app erpnext
        bench get-app --branch version-15 frappe
        bench get-app --branch version-15 https://github.com/your-username/payroll_indonesia.git

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test with pytest
      run: |
        pytest
