# .github/workflows/python-ci.yml
name: Python CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install bench
      run: |
        pip install -e git+https://github.com/frappe/bench.git#egg=bench
    
    - name: Setup Frappe environment
      run: |
        bench init --skip-redis-config-generation frappe-bench
        cd frappe-bench
        bench get-app erpnext
        # SOLUSI: Gunakan branch yang ada (misal version-14 atau develop)
        bench get-app --branch version-14 frappe
        # ATAU alternatif:
        # bench get-app --branch develop frappe
        bench get-app https://github.com/your-username/payroll_indonesia.git