# Python CI Workflow for Payroll Indonesia
# Last modified: 2025-05-11 11:29:53 by dannyaudianini
name: Python CI - Lint & Format

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Check Code Format with Black
      run: black --check .
      # This will fail if code is not correctly formatted according to Black
      
    - name: Flake8 Lint
      run: flake8 payroll_indonesia
      # This will fail if code has linting errors according to Flake8
      
    - name: Summary
      if: always()
      run: |
        echo "## Lint and Format Status" >> $GITHUB_STEP_SUMMARY
        echo "* Black formatting check: ${{ job.steps['Check Code Format with Black'].outcome }}" >> $GITHUB_STEP_SUMMARY
        echo "* Flake8 linting: ${{ job.steps['Flake8 Lint'].outcome }}" >> $GITHUB_STEP_SUMMARY